name: IICS CI Workflow
  # Following Project Variables must be defined in th CI/CD Configuration
  # IICS_QA_ORG_USER: ""
  # IICS_QA_ORG_PWD: ""
  # IICS_PROD_ORG_USER: ""
  # IICS_PROD_ORG_PWD: ""
  # AWS_ACCESS_KEY_ID: "" 
  # AWS_SECRET_ACCESS_KEY: ""
  # AWS_DEFAULT_REGION: ""


on: [push]

jobs:
  backup:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      env:
        IICS_QA_ORG_USER: ${{ secrets.IICS_QA_ORG_USER }}
        IICS_QA_ORG_PWD:  ${{ secrets.IICS_QA_ORG_PWD }}
        IICS_QA_TARGET_ENVIRONMENT: test
        IICS_QA_RELEASE_CONFIG: ./conf/iics.release.properties
        IICS_QA_PACKAGE_CONFIG: ./conf/all_designs.package.txt
        IICS_QA_TRANSFORM_CONFIG: ./conf/PennyMac_dev_test.transform.properties
        IICS_QA_PUBLISH_CONFIG: ./conf/all_designs.publish.txt
        IICS_QA_EXPORT_PATH: ./target/iics/export/test
        IICS_QA_EXPORT_FILE: IICS-iclab-AlertService

    - name: Build with Ant
      run: |
        ant download.src \
        -Diics.user.test="$IICS_PROD_ORG_USER" \
        -Diics.password.test="$IICS_PROD_ORG_PWD" \
        -Diics.release="$IICS_PROD_RELEASE_CONFIG" \
        -Diics.source.environment="$IICS_PROD_TARGET_ENVIRONMENT" \
        -Dtools.reporting.disabled=true \
